// HEGEMON — Unique units v2: three per playable civ (36 total).
// existing:true = already in data.ts (stats unchanged unless noted).
// basedOn = the common unit whose stat block is the template; mods are relative.
// unlockedBy = tech id (branch id from techs-v2.js, or trunk id with civLocked).
// Rock-paper-scissors categories unchanged: infantry/spear/heavy/mounted/ranged/siege/naval/support.

export const UNIQUE_UNITS = [
  // ROME — the professional army
  { id:"velites", civ:"rome", cat:"ranged", basedOn:"archer", unlockedBy:"castra", age:2,
    mods:{ move:+1, atk:-1, cheap:true, special:"may-retreat-after-attack-vs-melee" },
    role:"Skirmisher screen",
    note:"Young light troops with javelins and wolf-skin caps — harass, withdraw, repeat." },
  { id:"legionary", civ:"rome", cat:"heavy", existing:true, unlockedBy:"legionary-system", age:2,
    role:"Line backbone",
    note:"Pilum, gladius, scutum. The manipular system that ate the phalanx." },
  { id:"praetorian", civ:"rome", cat:"heavy", basedOn:"legionary", unlockedBy:"marian-reforms", age:3,
    mods:{ atk:+2, def:+2, cost:+50, cap:"max-2", special:"adjacent-friendlies+10-def" },
    role:"Elite guard",
    note:"The emperor's own. Expensive, political, and very hard to kill." },

  // CARTHAGE — money fights
  { id:"sacred-band", civ:"carthage", cat:"spear", basedOn:"spearman", unlockedBy:"suffete-council", age:2,
    mods:{ atk:+1, def:+2, cost:+30, special:"no-gold-purchase-citizen-only" },
    role:"Citizen elite",
    note:"2,500 sons of the noblest houses in white linen — the one corps Carthage never hired." },
  { id:"war-elephant", civ:"carthage", cat:"heavy", existing:true, unlockedBy:"war-elephants", age:2,
    role:"Shock breaker",
    note:"African forest elephants of the Atlas — smaller than India's, terrifying enough." },
  { id:"numidian-cavalry", civ:"carthage", cat:"mounted", basedOn:"horseman", unlockedBy:"numidian-alliance", age:3,
    mods:{ move:+1, def:-1, cheap:true, special:"may-retreat-after-attack" },
    role:"Harassing light horse",
    note:"No bridle, no saddle, no equal. They won Cannae's flanks." },

  // ATHENS (civ id 'greece') — the wooden wall
  { id:"hoplite", civ:"greece", cat:"spear", existing:true, unlockedBy:"hoplite-phalanx", age:2,
    role:"Citizen line",
    note:"Eight ranks of bronze and shield-wall discipline." },
  { id:"peltast", civ:"greece", cat:"ranged", basedOn:"archer", unlockedBy:"hoplite-phalanx", age:2,
    mods:{ move:+1, atkVsSpear:+25, special:"ignores-spear-first-strike" },
    role:"Anti-phalanx skirmisher",
    note:"Iphicrates' javelin men destroyed a Spartan mora in 390 BC — light beats heavy, sometimes." },
  { id:"athenian-trireme", civ:"greece", cat:"naval", basedOn:"trireme", unlockedBy:"neorion", age:2,
    mods:{ atk:+2, move:+1, special:"+25-vs-naval-in-friendly-coastal-waters" },
    role:"Elite ram",
    note:"200 free citizens rowing in time — Salamis was won below decks." },

  // EGYPT — the old kingdom's long arm
  { id:"war-chariot", civ:"egypt", cat:"mounted", existing:true, unlockedBy:"chariotry", age:2,
    role:"Mobile platform",
    note:"Driver and archer, wheels of the pharaohs." },
  { id:"nubian-archer", civ:"egypt", cat:"ranged", basedOn:"archer", unlockedBy:"nubian-archers", age:2,
    mods:{ atk:+2, range:"unchanged", cost:+20 },
    role:"Elite bow",
    note:"Ta-Seti, Land of the Bow — Egypt recruited the ancient world's best archers next door." },
  { id:"machimoi", civ:"egypt", cat:"spear", basedOn:"spearman", unlockedBy:"temple-estates", age:2,
    mods:{ cheap:true, def:+1, inOwnTerritory:true, special:"upkeep-paid-in-food-not-gold" },
    role:"Native levy",
    note:"The hereditary warrior class, paid in tax-free land — they fought for their fields." },

  // GAUL — fury and iron
  { id:"gaesatae", civ:"gaul", cat:"infantry", existing:true, unlockedBy:"iron-mastery", age:2,
    role:"Shock berserker",
    note:"Naked but for torc and shield at Telamon — mercenary spearmen of the Alps." },
  { id:"noble-horse", civ:"gaul", cat:"mounted", basedOn:"horseman", unlockedBy:"noble-cavalry", age:3,
    mods:{ atk:+2, cost:+20 },
    role:"Heavy tribal cavalry",
    note:"So good Rome simply hired them; late Roman cavalry was substantially Gallic." },
  { id:"soldurii", civ:"gaul", cat:"infantry", basedOn:"swordsman", unlockedBy:"client-warbands", age:3,
    mods:{ atk:+1, def:+1, special:"+15-when-stacked-with-another-gaul-unit" },
    role:"Sworn companions",
    note:"Oath-bound to share their lord's fate — none, Caesar noted, had ever broken it." },

  // PARTHIA — hammer, anvil, and the camel train
  { id:"horse-archer", civ:"parthia", cat:"ranged", existing:true, unlockedBy:"horse-archery", age:2,
    role:"Mobile fire",
    note:"Shoot, wheel, vanish. The Parthian way of war." },
  { id:"cataphract", civ:"parthia", cat:"heavy", basedOn:"horseman", unlockedBy:"cataphract-armouries", age:2,
    mods:{ def:+3, atk:+2, move:-1, cost:+40 },
    role:"Armoured anvil",
    note:"Man and horse in scale — the charge that ended what the arrows began." },
  { id:"camel-train", civ:"parthia", cat:"support", basedOn:"merchant", unlockedBy:"desert-waystations", age:2,
    mods:{ noAttack:true, special:"adjacent-friendly-ranged-units-never-run-dry:+heal2-and-ranged+10" },
    role:"Ammunition resupply",
    note:"Surena's thousand camels of arrows — the logistics that made Carrhae possible." },

  // SPARTA — the few
  { id:"spartiate", civ:"sparta", cat:"spear", basedOn:"hoplite", unlockedBy:"spartiate-corps", age:2,
    mods:{ atk:+2, def:+2, cost:+50, spawnsVet:1, cap:"max-4", special:"never-retreats" },
    role:"Elite hoplite",
    note:"Lambda on the shield. There were never many; there never needed to be." },
  { id:"perioikoi-hoplite", civ:"sparta", cat:"spear", basedOn:"spearman", unlockedBy:"perioikoi-crafts", age:2,
    mods:{ cheap:true },
    role:"Line filler",
    note:"The dwellers-around: free, un-citizen, and increasingly the bulk of every Spartan army." },
  { id:"skiritai", civ:"sparta", cat:"infantry", basedOn:"warrior", unlockedBy:"krypteia", age:2,
    mods:{ move:+1, vision:+1, special:"ignores-forest-hill-move-penalty, +25-in-fog" },
    role:"Scout corps",
    note:"Mountain men of Skiritis — the army's eyes, night guard, and left of the line." },

  // MACEDON — the machine
  { id:"phalangite", civ:"macedon", cat:"spear", basedOn:"spearman", unlockedBy:"sarissa-phalanx", age:2,
    mods:{ atk:+2, defVsFlank:-25, special:"+25-atk-vs-infantry-frontal" },
    role:"Pike block",
    note:"The six-metre sarissa: five rows of points before an enemy reaches the first man." },
  { id:"companion-cavalry", civ:"macedon", cat:"mounted", basedOn:"horseman", unlockedBy:"hetairoi", age:2,
    mods:{ atk:+3, cost:+40, special:"+25-when-attacking-a-unit-already-engaged" },
    role:"The hammer",
    note:"The wedge that broke every line Alexander pointed it at — with him at the tip." },
  { id:"hypaspist", civ:"macedon", cat:"infantry", basedOn:"swordsman", unlockedBy:"royal-pages", age:3,
    mods:{ atk:+1, def:+1, move:+1 },
    role:"Flexible elite",
    note:"The shield-bearers: fast enough to follow cavalry, solid enough to hold ground." },

  // PERSIA — the ten thousand and the wall of wicker
  { id:"immortal", civ:"persia", cat:"spear", basedOn:"spearman", unlockedBy:"immortals", age:2,
    mods:{ atk:+1, def:+1, special:"50pct-cost-refund-on-death" },
    role:"Replaceable elite",
    note:"Always ten thousand: every man lost was replaced by dawn. The unit never died." },
  { id:"sparabara", civ:"persia", cat:"ranged", basedOn:"archer", unlockedBy:"archer-corps", age:2,
    mods:{ def:+2, special:"no-ranged-retaliation-penalty-when-attacked-in-melee-first-round" },
    role:"Shielded bow line",
    note:"Wicker pavises in front, massed bows behind — a wall that shoots." },
  { id:"scythed-chariot", civ:"persia", cat:"mounted", basedOn:"horseman", unlockedBy:"engineering", civLocked:true, age:3,
    mods:{ atk:+3, def:-2, special:"+50-vs-ranged-units-on-open-terrain, -25-on-rough" },
    role:"Line breaker (situational)",
    note:"Blades on the axles. Devastating on flat ground, useless anywhere else — as at Gaugamela." },

  // HAN — the state arms itself
  { id:"crossbowman", civ:"han", cat:"ranged", basedOn:"archer", unlockedBy:"crossbow-production", age:2,
    mods:{ atk:+2, special:"target-terrain-defense-halved", move:-0, cost:+20 },
    role:"Armour piercer",
    note:"Bronze trigger locks precise enough to mass-produce; a conscript outshoots a lifetime archer." },
  { id:"han-cavalry", civ:"han", cat:"mounted", basedOn:"horseman", unlockedBy:"heavenly-horses", age:2,
    mods:{ atk:+1, def:+1, special:"+20-vs-mounted" },
    role:"Steppe answer",
    note:"Wudi's remade cavalry on Ferghana blood — built to beat the Xiongnu at their own game." },
  { id:"ji-halberdier", civ:"han", cat:"infantry", basedOn:"swordsman", unlockedBy:"iron-salt-monopoly", age:2,
    mods:{ atkVsMounted:+30, def:+1 },
    role:"Anti-cavalry infantry",
    note:"The ji: dagger-axe and spear in one — hook the rider, then finish it." },

  // MAURYA — chaturanga: the four arms
  { id:"armoured-elephant", civ:"maurya", cat:"heavy", basedOn:"war-elephant", unlockedBy:"elephant-corps", age:2,
    mods:{ def:+2, atk:+1, cost:+20, special:"carries-ranged-attack-(howdah-archers)" },
    role:"Moving fortress",
    note:"Indian elephants with plate and howdah — bigger than anything the west could field." },
  { id:"indian-longbow", civ:"maurya", cat:"ranged", basedOn:"archer", unlockedBy:"archery", civLocked:true, age:2,
    mods:{ atk:+2, special:"target-terrain-defense-halved", move:-0 },
    role:"Long-draw bow",
    note:"A man-tall bamboo bow braced on the ground — Arrian says nothing could stop the arrow." },
  { id:"kshatriya-chariot", civ:"maurya", cat:"mounted", basedOn:"horseman", unlockedBy:"imperial-army-scale", age:3,
    mods:{ atk:+2, special:"+10-to-adjacent-friendlies-(standard-bearer)" },
    role:"Command platform",
    note:"One of the four limbs of the chaturanga army — the word that became 'chess.'" },

  // SCYTHIA — everyone rides
  { id:"steppe-archer", civ:"scythia", cat:"ranged", basedOn:"archer", unlockedBy:"recurve-mastery", age:2,
    mods:{ mounted:true, move:+2, special:"may-move-after-attack" },
    role:"Mobile fire",
    note:"Every Scythian a mounted archer from childhood — the nation was the army." },
  { id:"royal-scythian", civ:"scythia", cat:"heavy", basedOn:"horseman", unlockedBy:"kurgan-rites", age:2,
    mods:{ def:+2, atk:+1, cost:+30 },
    role:"Noble lancer",
    note:"Scale armour of bronze plates sewn like fish skin — the kurgan graves are full of it." },
  { id:"amazon-rider", civ:"scythia", cat:"mounted", basedOn:"horseman", unlockedBy:"warrior-women", age:2,
    mods:{ move:+1, atk:+1, cheap:true },
    role:"Light lancer",
    note:"A third of armed steppe burials are women. The Greek legend had an address." },
];

// Model notes for board3d (procedural): every unique unit should read at a
// glance by SILHOUETTE, not detail — see HEGEMON-VISUALS-v2.md §2.
export const UNIT_SILHOUETTES = {
  velites:"small + javelin raised", praetorian:"legionary + tall crest + darker",
  "sacred-band":"white body + round shield", "numidian-cavalry":"small horse, no saddle blanket",
  peltast:"crescent shield (pelte)", "athenian-trireme":"trireme + bow eye + longer ram",
  "nubian-archer":"tall bow + dark palette", machimoi:"spearman + white kilt",
  "noble-horse":"horse + torc glint + cloak", soldurii:"paired-stance swordsman",
  cataphract:"horse fully skirted in scale", "camel-train":"two camels + bundles",
  spartiate:"red cloak + lambda shield", "perioikoi-hoplite":"plain hoplite, no cloak",
  skiritai:"hooded, crouched", phalangite:"very long pike at 45°",
  "companion-cavalry":"wedge pennant + purple cloak", hypaspist:"large round shield on back",
  immortal:"tiara + wicker shield", sparabara:"huge rectangular wicker pavise",
  "scythed-chariot":"chariot + axle blades", crossbowman:"horizontal bow silhouette",
  "han-cavalry":"horse + tassel", "ji-halberdier":"halberd with hook",
  "armoured-elephant":"elephant + boxy howdah", "indian-longbow":"bow taller than figure",
  "kshatriya-chariot":"4-horse chariot + banner", "steppe-archer":"rider twisted backward",
  "royal-scythian":"rider + scale glint + pointed cap", "amazon-rider":"light rider + pointed cap",
};
